micronaut:
    application:
        name: bank-transaction-service
    server:
        port: 8081
#        port: 8081 dev
#        prot: 8080 prod


datasources:
    default:
        url: ${JDBC_URL:`jdbc:mysql://xxx:3306/xxDB?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false`}
        username: ${JDBC_USER:sdf}
        password: ${JDBC_PASSWORD:%asdf,%}
        driverClassName: ${JDBC_DRIVER:com.mysql.jdbc.Driver}
        maximum-pool-size: 5
    tokdis:
        url: ${JDBC_URL:`jdbc:mysql://xxx:3306/xxDB?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false`}
        username: ${JDBC_USER:df}
        password: ${JDBC_PASSWORD:%asdf,%}
        driverClassName: ${JDBC_DRIVER:com.mysql.jdbc.Driver}
        maximum-pool-size: 5
    maintokdis:
        url: ${JDBC_URL:`jdbc:mysql://xxx:3306/xxDB?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false`}
        username: ${JDBC_USER:sdf}
        password: ${JDBC_PASSWORD:%sfsd.T%}
        driverClassName: ${JDBC_DRIVER:com.mysql.jdbc.Driver}
        maximum-pool-size: 5


#tag::jpa[] //untuk cek di folder bank.transaction.service.domainjpa jika ada setiap perubahan maka ada pembaruan table di database.
jpa:
    default:
        packages-to-scan:
            - 'bank.transaction.service.domain'
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5InnoDBDialect
                hbm2ddl:
                    auto: update
                show_sql: true
    tokdis:
        packages-to-scan:
            - 'bank.transaction.service.tokdis'
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5Dialect
                hbm2ddl:
                    auto: update
                show_sql: true
    maintokdis:
        packages-to-scan:
            - 'bank.transaction.service.tokdis'
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5Dialect
                hbm2ddl:
                    auto: update
                show_sql: true

#end::jpa[]